#!/bin/bash


# retrieve semantic version of latest tag for almalinux
read -r semver_tag <<< $(../utils/equate_tag_semver "library/almalinux:latest")
test -n ${semver_tag} || exit 1

DOCKER_BUILTKIT=1 docker build \
    --target jenkins_node \
    --tag ghcr.io/idigs/jenkins-node-alma:latest \
    --tag ghcr.io/idigs/jenkins-node-alma:${semver_tag} \
    --build-arg SEMVER_TAG=${semver_tag} \
  .

