

name: ramius
on: workflow_dispatch

jobs:
  job_debug:
    runs-on: ubuntu-latest
    steps:
      - if: true
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - if: true
        name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - if: true
        name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - if: true
        name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: dump shell env vars
        run: |
          env -0 | while IFS='' read -d '' line ; do printf '%s\t: %s\n' "${line%%=*}" "${line#*=}" | expand -t 30 | sed ':a;N;$!ba;s/\n/ /g'; done | LC_COLLATE=C sort -b

  job_setup:
    runs-on: ubuntu-latest
    steps:
      - id: semver_tag
        name: retrieve semantic version of latest tag
        run: |
          # Initial URL for the first page of the API
          next_url="https://hub.docker.com/v2/repositories/library/almalinux/tags/?page=1&page_size=100"

          paginated_results=()

          while [ -n "${next_url}" ]; do
            # fetch data and extract next_url and paginated tags list
            # --silent (-s) flag prevents curl from printing progress bars
            response=$(curl -s "${next_url}")

            # use jq to extract the next URL and append tags list
            # 'jq -r' flag outputs raw strings
            next_url=$(echo "${response}" | jq -r '.next')

            # append items from current page to the paginated_results
            # jq -c means flatten JSON output into a single line
            items=$(echo "${response}" | jq -c '.results')

            # append the current page's items to paginated results array
            while IFS= read -r item; do
              paginated_results+=("${item}")
            done <<< "${items}"
          done

          #
          # Output the combined array of all items as a single JSON object, then flatten and filter
          # to find the semantic version (x.y) tag that shares the same digest as the latest tag
          #
          printf 'semver_tag=%s\n' "${paginated_results[@]}" \
            | jq -r '.
              | flatten | map(del(.images)) | group_by(.digest) | .[]
              | select(.[].name == "latest") | .[]
              | select(.name | match("^\\d+.\\d+$"))
            ' >> $GITHUB_OUTPUT
    outputs:
      semver_tag: ${{ steps.semver_tag.outputs.tag }}



  job_docker:
    runs-on: ubuntu-latest
    needs: [ job_setup ]
    steps:
      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push - mantid development image
        uses: docker/build-push-action@v6
        with:
          context: ./Linux/development/docker
          push: true
          tags: ghcr.io/mantidproject/mantid-development-alma9:${{ needs.job_setup.outputs.semver_tag }}


